p001crud/crud01/urls.py
from django.urls import path
from . import views

app_name='crud01'

urlpatterns = [
    path('',views.task_list_and_create,name='crud_list'),
    path('update_task/<int:task_id>',views.update_task,name='update_task'),
]

p001crud/p001crud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud01/',include('crud01.urls',namespace='crud_list')),
]

p001crud/crud01/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    is_created = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

p001crud/crud01/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title','description']

p001crud/crud01/views.py
from django.shortcuts import render,redirect
from .models import Task
from .forms import TaskForm

def task_list_and_create(request):
    
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('crud01:crud_list')
    else:
        form = TaskForm()
    #tasks = Task.objects.all()
    complete_tasks = Task.objects.filter(is_created=True)
    incomplete_tasks = Task.objects.filter(is_created=False)



    return render(request, 'task_list.html',{
        'form':form,
     #   'tasks':tasks
        'complete_tasks':complete_tasks,
        'incomplete_tasks':incomplete_tasks
    })

def update_task(request,task_id):
    if request.method == 'POST':
        task = Task.objects.get(id=task_id)
        task.is_created = not task.is_created
        task.save()
        return redirect('crud01:crud_list')

# Create your views here.

p001crud/crud01/templates/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar Tarea</button>
    </form>

    <h2>Tareas Incompletas</h2>

    {% for task in incomplete_tasks %}
    
        <li>
            <div>
                <strong>{{task.title}}</strong> {{task.description}}
            </div>
            <div>
                <form action="{%url 'crud01:update_task' task.id%}" method="post">
                    {% csrf_token %}
                    <input type="checkbox" name="completed" onchange="this.form.submit()" {% if task.is_created %} checked {% endif %}>
                </form>
            </div>
            
        </li>
    {% empty %}
        <li>No hay tareas guardadas</li>
    {% endfor %}

    <h2>Tareas Completas</h2>
    
    {% for task in complete_tasks %}
    
        <li>
            <div>
                <strong>{{task.title}}</strong> {{task.description}}
            </div>
            <div>
                <form action="{%url 'crud01:update_task' task.id%}" method="post">
                    {% csrf_token %}
                    <input type="checkbox" name="completed" onchange="this.form.submit()" {% if task.is_created %} checked {% endif %}>
                </form>
            </div>
            
        </li>
    {% empty %}
        <li>No hay tareas guardadas</li>
    {% endfor %}

    
</body>
</html>